#!/usr/bin/env python3
"""Regenerate docs/threat-model.yaml from docs/threat-model.md.

The prose is canonical. This reads its tables and emits the sidecar, so the two
cannot drift: a hand-maintained companion goes stale on the first edit nobody
mirrors, and a stale sidecar is worse than none because a triage pipeline reads
it and the human reads the prose.

`prose_version` pins the SHA-256 of the exact prose bytes. A validator recomputes
it; if it does not match, the sidecar is stale and must be regenerated.

    python3 scripts/threat-model-sidecar.py [--check]

`--check` regenerates in memory and exits non-zero if the file on disk differs,
which is what CI wants.
"""
import collections
import hashlib
import json
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROSE = ROOT / "docs" / "threat-model.md"
SIDECAR = ROOT / "docs" / "threat-model.yaml"

DIMS = [
    "numeric-domain", "failure-atomicity", "recursive-cyclic-topology",
    "callback-execution", "serialization-reconstruction", "reference-lifecycle",
    "concurrency-reentrancy", "resource-complexity",
]

# What each claimed property is about. The prose states the property; this says
# which of the schema's fixed `kind` values it belongs to.
KIND = {
    "P1": "memory-safety", "P2": "correctness", "P3": "correctness", "P4": "integrity",
    "P5": "integrity", "P6": "integrity", "P7": "integrity", "P8": "integrity",
    "P9": "integrity", "P10": "integrity", "P11": "integrity", "P12": "integrity",
    "P13": "integrity", "P14": "integrity", "P15": "integrity", "P16": "confidentiality",
    "P17": "output-sanitization", "P18": "integrity", "P19": "correctness",
    "P20": "integrity", "P21": "integrity", "P22": "memory-safety", "P23": "integrity",
    "P24": "correctness", "P25": "resource-bound", "P26": "integrity",
    "P27": "correctness", "P28": "correctness", "P29": "resource-bound",
    "P30": "resource-bound", "P31": "integrity", "P32": "integrity", "P33": "integrity",
}

ADVERSARIES = [
    ("forged-attestation-attacker", "in",
     ["publish-a-package", "author-its-repository", "author-its-ci", "author-its-readme"],
     ["execute-in-trigon-process"], ["forged-equivalence-claim"], "docs/12-security.md §1.1"),
    ("prompt-injector", "in", ["write-text-a-model-reads"],
     ["execute-in-trigon-process"], ["steer-a-strategy"], "docs/12-security.md §4"),
    ("malformed-input-author", "in", ["supply-hostile-artifact-bytes"], [],
     ["panic", "resource-exhaustion"], "docs/05-archive-and-normalization.md §2.2"),
    ("definitions-contributor", "in", ["open-a-pull-request"], ["merge-without-review"],
     ["erase-a-real-difference"], "docs/12-security.md §8"),
    ("second-package-attacker", "in", ["publish-a-second-package"], [],
     ["reach-payload-through-an-allowlisted-host"], "docs/17-backlog.md B7"),
    ("normalization-conditioned-attacker", "in",
     ["condition-payload-on-a-normalized-observable"], [], ["match-while-differing"],
     "docs/05-archive-and-normalization.md §1"),
    # A8 and A9 are adversaries of the evidence store docs/19 designs. Its reader is built as
    # `verify-attestation --record` (P31-P33); §1.10 routes a finding against the rest by §1.3.
    ("evidence-repository-operator", "in",
     ["hold-the-attestation-key", "hold-the-log-key", "hold-the-push-credential",
      "rewrite-repository-history", "serve-different-clients-different-logs"],
     ["change-a-checkpoint-a-client-already-holds"],
     ["publish-a-record-clients-accept", "silently-retract-a-record", "equivocate"],
     "docs/19-distribution-and-lookup.md §8"),
    ("stale-or-split-view-host", "in",
     ["serve-an-old-clone", "withhold-a-newer-checkpoint",
      "serve-different-clients-different-histories"],
     ["sign-a-checkpoint", "sign-a-record"],
     ["turn-a-withdrawal-back-into-a-verdict", "split-view"],
     "docs/19-distribution-and-lookup.md §6.1, §7, §8"),
    ("operator", "out", ["pass-any-flag", "name-a-local-source", "supply-a-key"], [], [],
     "docs/16-findings.md §3.7"),
    ("in-process-code-execution", "out", ["execute-in-trigon-process"], [], [],
     "docs/threat-model.md §1.10"),
    ("compromised-control-plane", "out", ["compromise-scheduler-and-attestor"], [], [],
     "docs/12-security.md §11"),
    ("shared-installation-tenant", "out", ["share-an-installation"], [], [],
     "docs/12-security.md §7"),
]

HEADER = """# threat-model.yaml — derived index; docs/threat-model.md is canonical.
#
# GENERATED by scripts/threat-model-sidecar.py. Do not hand-edit: edit the prose
# and regenerate, or the two drift and the pipeline reads something the human
# never approved.
#
# prose_version pins the SHA-256 of the exact prose bytes this derives from.
#
# Automated triage MUST enforce provenance: a record whose provenance.kind is
# `inferred` or `assumption` may suggest escalation and may never authorize a
# closing disposition, whatever model_status says. See x-non-closing-outcome.
"""


def section(src, n):
    m = re.search(rf"^## {re.escape(n)}\b.*?$(.*?)(?=^## |\Z)", src, re.M | re.S)
    return m.group(1) if m else ""


def rows(block, ncols):
    """Table rows with exactly ncols cells, minus the header and rule lines."""
    skip = {"ID", "Family", "Entry point", "Knob", "Effect", "Channel", "Dependency",
            "Tag", "Role", "Item", "Disposition", "`12-security.md`"}
    out = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("|") or set(line) <= set("|- :"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != ncols or cells[0].startswith("---") or cells[0] in skip:
            continue
        out.append(cells)
    return out


def prov(text):
    m = re.search(r"\*\((documented|maintainer|assumption|inferred)(?:, ([^)]*))?\)\*", text)
    if not m:
        return {"kind": "documented", "source": "docs/threat-model.md"}
    kind, rest = m.group(1), (m.group(2) or "").strip()
    if kind == "documented":
        return {"kind": "documented", "source": rest or "docs/threat-model.md"}
    if kind == "maintainer":
        return {"kind": "maintainer", "date": rest}
    return {"kind": kind, "question_id": rest}


def clean(t):
    t = re.sub(r"\*\((documented|maintainer|assumption|inferred)[^)]*\)\*", "", t)
    t = re.sub(r"[*`]", "", t)
    return re.sub(r"\s+", " ", t).strip(" .;,")


def census(src):
    """Claim tags only — the legend rows are excluded by starting after them."""
    body = src.split("**What a tag is allowed to do.**", 1)[1]
    return {
        "documented": len(re.findall(r"\*\(documented[,)]", body)),
        "maintainer": len(re.findall(r"\*\(maintainer,", body)),
        "inferred": len(re.findall(r"\*\(inferred, Q", body)),
        "assumption": len(re.findall(r"\*\(assumption, Q", body)),
    }


def build(src):
    comps, reach = [], {}
    for c in rows(section(src, "1.4"), 2):
        reach[re.sub(r"\s*\(.*", "", clean(c[0]))] = clean(c[1])
    for c in rows(section(src, "1.2"), 4):
        name = re.sub(r"\s*\(.*", "", clean(c[0]))
        scope = "in" if c[3].lower().lstrip("*").startswith("in") else "out"
        entry = {"name": name, "scope": scope,
                 "reachability_precondition": reach.get(name, "see docs/threat-model.md §1.4"),
                 "provenance": {"kind": "documented", "source": "docs/threat-model.md §1.2"}}
        if scope == "out":
            entry["reason"] = "not shipped in any binary, per §1.3"
        comps.append(entry)

    cd = []
    for c in rows(section(src, "1.7"), 5):
        if c[1] not in DIMS and not c[1].startswith("x-"):
            continue
        st = clean(c[2]).lower()
        status = ("disclaimed" if "disclaimed" in st
                  else "claimed" if "claimed" in st else "not-applicable")
        row = {"component": clean(c[0]), "dimension": c[1], "status": status,
               "conditions": clean(c[3])}
        owner = clean(c[4])
        if status in ("claimed", "disclaimed") and owner and owner != "—":
            row["property_id"] = owner.split(",")[0].strip()
        row["provenance"] = {"kind": "documented", "source": "docs/threat-model.md §1.7"}
        cd.append(row)

    owners = collections.defaultdict(set)
    for r in cd:
        if "property_id" in r:
            owners[r["property_id"]].add(r["component"])

    claimed = []
    for c in rows(section(src, "1.11"), 5):
        pid = clean(c[0])
        if not re.fullmatch(r"P\d+", pid):
            continue
        claimed.append({
            "id": pid, "kind": KIND.get(pid, "integrity"),
            "components": sorted(owners.get(pid, {"multiple"})),
            "tier": "security-critical" if "security-critical" in c[4] else "correctness-only",
            "conditions": clean(c[2]) or "all supported configurations",
            "violation_symptoms": [x.strip() for x in clean(c[3]).split(";") if x.strip()] or ["wrong-output"],
            "statement": clean(c[1])[:400], "provenance": prov(c[4])})

    disclaimed = []
    for c in rows(section(src, "1.12"), 5):
        did = clean(c[0])
        if not re.fullmatch(r"D\d+", did):
            continue
        disclaimed.append({
            "id": did, "components": sorted(owners.get(did, {"multiple"})),
            "conditions": clean(c[2]) or "all supported configurations",
            "tier": "security-critical" if "security-critical" in c[3] else "correctness-only",
            "false_friend": False, "statement": clean(c[1])[:400], "provenance": prov(c[4])})

    ff_block = re.search(r"### False friends.*?\n(.*?)### Properties simply", src, re.S).group(1)
    for n, m in enumerate(re.finditer(r"^- \*\*(.+?)\*\*(.*?)(?=\n- |\Z)", ff_block, re.M | re.S), 1):
        raw = re.sub(r"\s+", " ", m.group(1) + " " + m.group(2)).strip()
        disclaimed.append({
            "id": f"FF{n}", "components": ["multiple"],
            "conditions": "all supported configurations", "tier": "correctness-only",
            "false_friend": True, "statement": clean(raw)[:300], "provenance": prov(raw)})

    responsibilities = []
    d13 = section(src, "1.13")
    for i, m in enumerate(re.finditer(r"^\d+\.\s+\*\*(.+?)\*\*(.*?)(?=\n\d+\. |\n\*\*|\Z)",
                                      d13, re.M | re.S), 1):
        responsibilities.append({
            "id": f"dr-{i}", "component": "multiple",
            "statement": clean(m.group(1) + " " + m.group(2))[:300],
            "enforces": sorted(set(re.findall(r"\b([PD]\d+)\b", m.group(0)))),
            "provenance": {"kind": "documented", "source": "docs/threat-model.md §1.13"}})

    misuses = []
    for i, m in enumerate(re.finditer(r"^- \*\*(.+?)\*\*(.*?)(?=\n- |\Z)",
                                      section(src, "1.14"), re.M | re.S), 1):
        misuses.append({
            "id": f"km-{i}", "component": "multiple", "pattern": clean(m.group(1))[:220],
            "safer_alternative": clean(m.group(2))[:220] or "see docs/threat-model.md §1.14",
            "provenance": {"kind": "documented", "source": "docs/threat-model.md §1.14"}})

    knf = []
    for c in rows(section(src, "1.15"), 3):
        nid = clean(c[0])
        if not re.fullmatch(r"N\d+", nid):
            continue
        knf.append({
            "id": nid, "component": "multiple", "tool_pattern": clean(c[1])[:300],
            "conditions": "matches on every field; a stated bypass is excluded",
            "discharged_by": sorted(set(re.findall(r"\b([PD]\d+)\b", c[2]))) or ["see §1.15"],
            "provenance": {"kind": "documented", "source": "docs/threat-model.md §1.15"}})

    flags = []
    for c in rows(section(src, "1.6"), 4):
        name = clean(c[0])
        if not name:
            continue
        stance = clean(c[2]).lower()
        flags.append({
            "name": name, "default": clean(c[1]), "security_relevant": True,
            "maintainer_stance": "dev-only" if "dev-only" in stance else "supported",
            "affects_properties": [{"property_id": "P11",
                                    "effect": "voids" if "voids" in stance else "preserves"}],
            "provenance": prov(c[3])})

    outputs = []
    for c in rows(section(src, "1.8"), 4):
        p = prov(c[3]) if "*(" in c[3] else {"kind": "documented",
                                             "source": "docs/threat-model.md §1.8"}
        outputs.append({
            "component": "multiple", "channel": clean(c[0]),
            "taint": "same-as-input" if "same as input" in c[1].lower() else "constrained",
            "taint_provenance": p, "invariants": [],
            "downstream_must_not_assume": [{"id": f"mna-{len(outputs) + 1}",
                                            "statement": clean(c[3])[:300], "provenance": p}]})

    deps = []
    for c in rows(section(src, "1.9"), 4):
        name = clean(c[0])
        if not name:
            continue
        deps.append({
            "name": name, "relied_on_for": clean(c[1])[:220], "relied_on_properties": [],
            "caller_obligations_acknowledged": [], "adversary_capabilities_forwarded": [],
            "outputs_consumed": [], "covered_here": False,
            "violation_disposition": "OUT-OF-MODEL: dependency-contract",
            "provenance": prov(c[2])})

    eps = {}
    for c in rows(section(src, "1.7"), 6):
        ep = clean(c[0])
        if not ep:
            continue
        atk = c[2].lower().lstrip("*").startswith("yes")
        eps.setdefault(ep, {"id": ep, "component": "multiple", "parameters": []})
        eps[ep]["parameters"].append({
            "name": clean(c[1]), "attacker_controllable": atk,
            "control_kinds": [k.strip() for k in clean(c[3]).split(",") if k.strip()] or ["data"],
            "caller_must_enforce": clean(c[4]) or "none", "provenance": prov(c[5])})

    effects = []
    for c in rows(section(src, "1.5"), 3):
        eff = clean(c[0])
        if not eff:
            continue
        st = c[1].lower()
        effects.append({
            "effect": eff,
            "stance": "absent" if "absent" in st else "conditional" if "conditional" in st else "present",
            "components": [], "conditions": clean(c[2]), "provenance": prov(c[2])})

    return {
        "schema": "threat-model-sidecar/v2",
        "project": "trigon",
        "prose_version": f"docs/threat-model.md@sha256:{hashlib.sha256(PROSE.read_bytes()).hexdigest()}",
        "model_status": "unratified-draft",
        "triage_policy": "strict",
        "confidence": census(src),
        "components": comps,
        "host_side_effects": effects,
        "entry_points": list(eps.values()),
        "contract_dimensions": cd,
        "outputs": outputs,
        "adversaries": [{"name": n, "scope": s, "capabilities": cap,
                         "excluded_capabilities": ex, "goals": g,
                         "provenance": {"kind": "documented", "source": src_}}
                        for n, s, cap, ex, g, src_ in ADVERSARIES],
        "dependency_policy": {"zero_runtime_dependencies": False,
                              "provenance": {"kind": "documented",
                                             "source": "crates/*/Cargo.toml; no vendor/ or third_party/ at any path"}},
        "dependencies": deps,
        "build_policy": {"security_relevant_flags_present": True,
                         "provenance": {"kind": "documented",
                                        "source": "crates/trigon/Cargo.toml [features]"}},
        "build_flags": flags,
        "properties_claimed": claimed,
        "properties_disclaimed": disclaimed,
        "downstream_responsibilities": responsibilities,
        "known_misuses": misuses,
        "known_non_findings": knf,
        "dispositions": [
            "VALID", "VALID-HARDENING", "OUT-OF-MODEL: trusted-input",
            "OUT-OF-MODEL: adversary-not-in-scope", "OUT-OF-MODEL: unsupported-component",
            "OUT-OF-MODEL: non-default-build", "OUT-OF-MODEL: dependency-contract",
            "BY-DESIGN: property-disclaimed", "KNOWN-NON-FINDING", "MODEL-GAP"],
        "disposition_precedence": [
            "KNOWN-NON-FINDING", "OUT-OF-MODEL: unsupported-component",
            "OUT-OF-MODEL: non-default-build", "OUT-OF-MODEL: dependency-contract",
            "OUT-OF-MODEL: trusted-input", "OUT-OF-MODEL: adversary-not-in-scope",
            "BY-DESIGN: property-disclaimed", "VALID", "VALID-HARDENING", "MODEL-GAP"],
        "x-non-closing-outcome": {
            "name": "ESCALATE: unratified-claim",
            "meaning": "the matched rule is licensed only by an inferred or assumption claim; "
                       "it escalates to the maintainer and never closes a report",
            "encoded_structurally_as": "provenance.kind in [inferred, assumption]"},
    }


def coverage(doc):
    """Every in-scope component needs a row for each of the eight dimensions."""
    have = collections.defaultdict(set)
    for r in doc["contract_dimensions"]:
        have[r["component"]].add(r["dimension"])
    gaps = {}
    for c in doc["components"]:
        if c["scope"] != "in":
            continue
        missing = [d for d in DIMS if d not in have.get(c["name"], set())]
        if missing:
            gaps[c["name"]] = missing
    orphans = sorted(set(have) - {c["name"] for c in doc["components"]})
    return gaps, orphans


def main():
    src = PROSE.read_text()
    doc = build(src)

    gaps, orphans = coverage(doc)
    if gaps or orphans:
        for name, missing in gaps.items():
            print(f"missing dimension rows for {name}: {', '.join(missing)}", file=sys.stderr)
        for name in orphans:
            print(f"matrix row for a component not in §1.2: {name}", file=sys.stderr)
        return 1

    text = HEADER + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True,
                                   width=100, default_flow_style=False)
    if "--check" in sys.argv:
        if not SIDECAR.exists() or SIDECAR.read_text() != text:
            print("docs/threat-model.yaml is stale; run scripts/threat-model-sidecar.py",
                  file=sys.stderr)
            return 1
        print("docs/threat-model.yaml is current")
        return 0

    SIDECAR.write_text(text)
    n = doc["confidence"]
    print(f"wrote {SIDECAR.relative_to(ROOT)}: "
          f"{len(doc['components'])} components, {len(doc['contract_dimensions'])} dimension rows, "
          f"{len(doc['properties_claimed'])} claimed, {len(doc['properties_disclaimed'])} disclaimed")
    print(f"census: {n['documented']} documented / {n['maintainer']} maintainer / "
          f"{n['assumption']} assumption / {n['inferred']} inferred")
    return 0


if __name__ == "__main__":
    sys.exit(main())
